### ISSUE TITLE
Tracking issue for updating documentation

### ISSUE THREAD

**Issue by Enzime** [LnL7/nix-darwin#1155]
- [ ] Make flakes recommended
- [ ] Combine flakes and non-flake sections
  - [ ] Write configuration
  - [ ] Add `darwin` to `NIX_PATH`
  - [ ] Installation (`darwin-rebuild` for flakes, `darwin-installer` for non-flakes)
  - [ ] Using nix-darwin
  - [ ] Updating nix-darwin
  - [ ] Uninstalling
