### ISSUE TITLE
Tracking issue for deprecating installer

### ISSUE THREAD

**Issue by Enzime** [LnL7/nix-darwin#1156]
- [ ] Replace copying the default configuration with instructions in README, see #1177
- [x] Change `services.nix-daemon.enable` to default to `true` and add sufficient checks to tell users to set it to `false` if they are using single-user mode, see #1164 
- [ ] Replace setting up `darwin` channel with instructions in README, see #1177
- [ ] Test `nix run nix-darwin -- switch -I darwin-config=~/.nixpkgs/darwin-configuration.nix`, see #1177
- [ ] Replace installer with `darwin-rebuild switch` command in README, see #1177
- [ ] Ensure `/etc/synthetic.conf` always contains `run` if `sw_vers > 10.15`, see #1177

**Comment by Enzime** [comment]
Not sure if we should change `darwin-rebuild` to default `<darwin>` to the nix-darwin it comes from

If we do that, then we could even automate adding the `darwin` channel as part of activation, rather than requiring users to manually do it

**Comment by emilazy** [comment]
Wouldn’t that pin an exact commit when used through `nix run`?

**Comment by Enzime** [comment]
Only if the user doesn't have `<darwin>` configured in their channels

We could also add an option like `nix.configureDarwinChannel = true;` which runs:

```
$ nix-channel --add https://github.com/LnL7/nix-darwin/archive/master.tar.gz darwin
```
