### ISSUE TITLE
Tracking issue for changing the default configuration folder

### ISSUE THREAD

**Issue by Enzime** [LnL7/nix-darwin#1203]
- [x] Change `environment.darwinConfig` to `/etc/nix-darwin` in a new `system.stateVersion`
- [x] Change `darwin-rebuild` to use `/etc/nix-darwin/configuration.nix`
- [ ] Add a check for users on old `system.stateVersion` to ensure `environment.darwinConfig` is correctly set 
- [x] Update README to use `/etc/nix-darwin` for flakes
- [x] Update README to use `/etc/nix-darwin` for channels

**Comment by Enzime** [comment]
Prior to #741, there was no default folder to search for a flake nix-darwin configuration in

**Comment by emilazy** [comment]
I think we’ve basically done this by now?

**Comment by Enzime** [comment]
Yeah I think so
