### ISSUE TITLE
Tracking issue for improving launchd

### ISSUE THREAD

**Issue by Enzime** [LnL7/nix-darwin#1219]
- [ ] Make sure all nix-darwin managed units are loaded in
- [ ] Back up existing files before replacing them
- [ ] Restore backed up files when uninstalling nix-darwin

**Comment by Samasaur1** [comment]
Should this also include the work that needs to be done to have them show with nicer names in System Settings, or should that be its own tracking issue?

**Comment by Enzime** [comment]
Updated 👍

**Comment by lloeki** [comment]
> Replace usage of {un,}load and boot{out,strap}

I've opened an issue heavily related to that, because for `LaunchAgents` it can get tricky: https://github.com/LnL7/nix-darwin/issues/1255

**Comment by lloeki** [comment]
> copies that binary somwhere not in the Nix store

I'm curious, why is that?

**Comment by Samasaur1** [comment]
> > copies that binary somwhere not in the Nix store
> 
> I'm curious, why is that?

For the same reason that our current implementation uses `wait4path`: if the executable is on a volume that isn't the root, and that volume hasn't mounted by the time the launchagent or launchdaemon starts, the service will fail repeatedly until it is put in the "penalty box" and then won't start at all. By copying the binary onto the root volume, we avoid this error, and then that binary waits for the Nix store before running the *actual* executable

**Comment by lloeki** [comment]
Ah yes of course, what a brain glitch on my part.

**Comment by lukahasch** [comment]
i have just run into this issue but sadly do not have the skill to fix it, so i just wanna express my interest in this getting fixed
