### ISSUE TITLE
Tracking issue for improving uninstalling

### ISSUE THREAD

**Issue by emilazy** [LnL7/nix-darwin#730]
Just off the top of my head:
- [x] Needs to clean up `/run`, esp. after https://github.com/LnL7/nix-darwin/pull/687
- [x] Didn't delete `/Applications/Nix Apps`
- [x] Should restore pre-nix-darwin configuration like `nix.conf`, `bashrc` and `zshrc`
- [x] Change user shells that point to `/run/current-system`
- [x] Flake uninstall procedure needs documenting in README
- [x] Update documentation to try running the uninstaller from `$PATH`

**Comment by Enzime** [comment]
I've fixed `/Applications/Nix Apps` not getting deleted in #687.

As opposed to the installer, I think uninstalling a flake-based system can be handled by the `darwin-uninstaller`, need to investigate further into any additional flake-specific logic that needs to be added.

**Comment by emilazy** [comment]
> I've fixed `/Applications/Nix Apps` not getting deleted in #687.

That's what confuses me: I was using that version (`nix run github:Enzime/...`).

**Comment by Enzime** [comment]
I believe the uninstaller is not unloading launchd daemons before deleting the files, need to check this further.

**Comment by zdcthomas** [comment]
I thought I'd call this out here too, there's a small bootstrapping issue with the uninstaller being a derivation that has to be built to be run. If someone has any issues actually running nix, and they want to uninstall nix-darwin to get back to a clean state, they can't easily do that right now, since the docs recommend running from the derivation

**Comment by Enzime** [comment]
Some progress was made on this as of #806 as the uninstaller is now installed by default on all `nix-darwin` systems, accessible through `darwin-uninstaller`, so it no longer needs to be built, however I believe the uninstaller still depends on Nix.

The documentation should probably be updated to recommend running the uninstaller from `$PATH`

**Comment by Enzime** [comment]
Another thing to consider is what we want to do with users and groups created or managed by nix-darwin

**Comment by tgallacher** [comment]
Trying to uninstall nix-darwin so that I can uninstall determinate nix. When transferring my laptop I forgot to say "no" during the determinate systems installer to not install determinate nix, as their installer + docs really push their way as the "recommended" way. But I want nix-darwin to control my nix install.

First issue I ran into was not having `darwin-uninstaller` on my path. Had to run: 

```sh
sudo nix --extra-experimental-features "nix-command flakes" run 'nix-darwin#darwin-uninstaller'
```

The uninstaller fell over due to the presence of `/Applications/Nix Apps`, as it appears it wants to create that dir and it already existed, even though its "uninstalling" nix-darwin? After manually removing that dir, the uninstaller then ran to completion (but also re-created the "Nix Apps" dir?)

Rebooted laptop and tried to uninstall determinate nix, but it failed due to detecting a `nix-darwin` install... And now I'm trapped, the nix-darwin uninstaller doesn't do anything different on subsequent runs and determinate nix always complains I still have nix-darwin installed. 

Output from the `nix-darwin` uninstaller:


```
Uninstalling nix-darwin, this will:

    - remove /Applications/Nix Apps symlink
    - cleanup static /etc files
    - disable and remove all launchd services managed by nix-darwin

Proceed? [y/n] y
setting up /run via /etc/synthetic.conf...
setting up /Applications/Nix Apps...
warning: /Applications/Nix Apps is not owned by nix-darwin, skipping App linking...
setting up pam...
applying patches...
setting up /etc...
setting up launchd services...
configuring networking...
configuring power...
setting up /Library/Fonts/Nix Fonts...
setting nvram variables...
warning: nix-channel is deprecated in favor of flakes in Determinate Nix. See https://zero-to-nix.com for a guide to Nix flakes. For details and to offer feedback on the deprecation process, see: https://github.com/DeterminateSystems/nix-src/issues/34.
warning: selector 'darwin' matched no installed derivations
NOTE: the /run symlink will be removed on reboot

NOTE: The /nix/var/nix/profiles/system* profiles still exist and won't be garbage collected.

Done!
``` 

_Edit: It seems determinate nix isn't happy this this still exists `launchctl print system/org.nixos.activate-system`_

**Comment by tgallacher** [comment]
In case this helps someone else, the solution was actually pretty simply. 

The Determinate system uninstaller only checks for the presence of a service, and so the fact that nix-darwin stops the service on uninstall doesn't matter: the determinate uninstaller still falls over. 

To fix, I ran:

```sh
launchctl bootout system/org.nixos.activate-system
```

Then I could run the Determinate uninstaller and start fresh, using upstream nix with nix-darwin. 

_Now, to sort out a suitable installer when determinate remove upstream nix support within their installer in Jan..._
